### ISSUE TITLE
Add zone support

### ISSUE THREAD

**Issue by reinder** [traintastic/traintastic#144]
### What is a zone

A zone is a group of blocks, a block can be part of multiple zones.

### What is the use case

Zones can be used to apply certain limitations to a group of blocks, e.g. force mute for the staging area or apply a speed limit to the shunting area. The zone can also track which trains are in the zone, are entering/approaching the zone and are leaving the zone, e.g. as informational list for each operator of a layout section.

### Tasks

- [x] Basic zone implementation: object creation, add/remove blocks
- [x] Train tracking for zone
- [x] Zone events: train assigned/entering/entered/leaving/left/removed
- [x] Train events: zone assigned/entering/entered/leaving/left/removed
- [x] Mute option
- [x] No smoke option
- [x] Speed limit option, related #153
- [x] Icon for GUI
- [x] Manual
- [x] Lua documentation
- [x] Highlight zone on board
