### ISSUE TITLE
Z21 Emulator issues

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#50]
# Z21 Server Emulator
Hi, this is a generic issue for compatibility with [Z21ServerEmulator](https://github.com/gfgit/Z21ServerEmulator) based on Philipp Gahtow's work

## New hardware types
- [x] Recognize newer hardware types (See #49 )

## Fix Broadcast flags
The Z21 is not correctly receiving `LAN_SET_BROADCASTFLAGS` sent here [clientkernel.cpp#L408](https://github.com/traintastic/traintastic/blob/dae4eea927aa0224f4840b60b584a900b3fba4aa/server/src/hardware/protocol/z21/clientkernel.cpp#L408)

This results in Z21 not informing Traintastic of S88 feedback status for example.

**Temporary workaround:** send UDP synchronously: change here [udpclientiohandler.cpp#L76](https://github.com/traintastic/traintastic/blob/dae4eea927aa0224f4840b60b584a900b3fba4aa/server/src/hardware/protocol/z21/iohandler/udpclientiohandler.cpp#L76) to `m_socket.send_to(...)`
This of course is not a good solution, other options:
- Add a delay between messages to prevent UDP skipping datagrams
- Send Broadcast flags multiple times at regular interval until we get a response (maybe integrate with keep alive timer to avoid multiple messages)

- [x] See #51 for second option

## Configurable Keep Alive Timer

While debugging this message is really annoying if for example I set a breakpoint on Z21's `receive()` or Traintastic's `send()`
So for debugging purposes the time interval could be set to 30 seconds or entirely disabled?

## Short Circuit detection

Traintastic is ignoring short circuit power state messages. This may be because `World` has no equivalent concept.
But instead of ignoring it and pretending trains are still running I would map it to `PowerOff` like for `TrackVoltageOff` message.

- [x] See second commit of #49 

## Power state not read on connection
When enabling connection, the Z21 sends current power state to every new client, but server does not receive it.
Possible solutions:
- [ ] Handle `LAN_SYSTEMSTATE_DATACHANGED` which is the reply of keep alive timer
This means PR #51 must be modified to use a second timer instead of reusing the same!
Or use the same timer to ask for both but this way we could again get UDP skipping packets which is the original issue...

EDIT: it seems to work now but still might be a good idea to handle that message
See second commit of #51 

## Emergency Stop while Power Off
If I click on Power Off, the "Stop/Run" goes to Stop and Z21 receives `X_SET_TRACK_POWER_OFF`.
But then if I click on Stop, the Z21 receives `X_SET_STOP` which seems to imply track power is back on but trains are stopped.
This means out of sync state between server and traintastic

## LanXLocoInfo ##
`LAN_X_LOCO_INFO` has variable size. It has n + 1 (+1 because it starts from db0) with `7 <= n <= 14` data bytes + xHeader + XOR + Z21 header (4 bytes)
Which make a total of `13 <= x <= 20` bytes.
XPressNet Checksum fails because assumes always 15 bytes data, (`xHeader & 0x0F = 0xEF & 0x0F = 15`)
but it can be less, like 7 bytes data + xHeader + XOR (don't know if XOR is considered in those 15 or not)
Variable size is mainly for future extension and higher decoder function numbers.
- [x] Done as part of PR #82 

## Crash when disabling communications ##
Still have to investigate but exception is thrown by Z21 log all pachets -> `basic_string::M_create` then an assert fires in destructors.

**Comment by gfgit** [comment]
> p.s.2. I usually just disabled the keep alive timer when debugging Z21 stuff, we could add an option to configure it, but if it is only for development I prefer not to bother the user with it. (One option less to explain ;))

Yes but with MinGW even for 1 line change like that it takes ages to compile and link the server. I need to try other compilers.


> I prefer to keep it async, else the kernel thread is blocked. We could however add some additional monitoring to check if the broadcast flags are set correctly, else it should retry. After all it is UDP, so no guarantee if it is received.

I'm testing replacing keep alive timer with BC flag request until we get a valid response, then it becomes the usual keep alive timer.
The new `LanGetBroadcastFlagsReply` looks similar to `LanSetBroadcastFlags` but for now I kept them separate

**Comment by reinder** [comment]
> Yes but with MinGW even for 1 line change like that it takes ages to compile and link the server. I need to try other compilers.

On windows I use clang / msvc, I installed the VS2019 Community edition for that. VS2019 has Cmake support too, but I use VScode for development, like I do on Linux.

> The new `LanGetBroadcastFlagsReply` looks similar to `LanSetBroadcastFlags` but for now I kept them separate

I like that, then it is easier to understand when reading the code :)

Note: If different behavior is needed based on the command station that is communicated with, please add a setting for every *tweak* that is required. A *command station* property can be added which sets the proper options for the selected command station. (for LocoNet this is already used)

**Comment by gfgit** [comment]
> Note: If different behavior is needed based on the command station that is communicated with, please add a setting for every _tweak_ that is required. A _command station_ property can be added which sets the proper options for the selected command station. (for LocoNet this is already used)

To better understand this aspect: is the behavior changing or it's only about the communication aspect?
Because all the LocoNet different `IOHandler`s then call `Kernel::receive()` which is not aware of the source so it cannot change behavior I guess...

**Comment by gfgit** [comment]
Why some mesages like `LanXBCTrackPowerOff` do not have `ATTRIBUTE_PACKED`?

**Comment by gfgit** [comment]
Also I propose to use `LAN_X_BC` in `ClientKernel::receive()` switch/case for `switch(lanX.xheader)` and also the other values.
I'm trying to implement `LAN_X_TURNOUT_INFO` message so now `LanXGetTurnoutInfo` constructor can use `LAN_X_TURNOUT_INFO` constant

**Comment by gfgit** [comment]
`LanXSetTurnout` address bit shifting is different from `LanXGetTurnoutInfo` which follows protocol document.
From Z21 side I receive an address "0" for first output and strange addresses for subsequent outputs.
Then when I get `LAN_X_TURNOUT_INFO` back in traintastic server the address 0 is not a valid address, outputs start from 1

**Comment by reinder** [comment]
> Why some mesages like `LanXBCTrackPowerOff` do not have `ATTRIBUTE_PACKED`?

Because I forgot somehow, please add them :)

> Also I propose to use LAN_X_BC in ClientKernel::receive() switch/case for switch(lanX.xheader) and also the other values.
I'm trying to implement LAN_X_TURNOUT_INFO message so now LanXGetTurnoutInfo constructor can use LAN_X_TURNOUT_INFO constant

Yes sure! Good suggestion :) (Don't know why I didn't do that...)

> LanXSetTurnout address bit shifting is different from LanXGetTurnoutInfo which follows protocol document.
From Z21 side I receive an address "0" for first output and strange addresses for subsequent outputs.
Then when I get LAN_X_TURNOUT_INFO back in traintastic server the address 0 is not a valid address, outputs start from 1

Traintastic uses linear addressing, usually 1...max.Many systems use an addressing scheme that groups two outputs. So 1 -> 1.1, 2 -> 1.2, 3 -> 2.1, 4 -> 2.2. 

It is possible that there is an offset in this. I don't have a real Z21 to test against. I have a Digikeijs DR5000 which supports the protocol, I can test with that one and you can test with the Z21 implementation you got. Then we can check if they are compatible.

Addressing is always a bit tricky. (I know of other software that has some options to tweak addressing issues.)

**Comment by gfgit** [comment]
> Traintastic uses linear addressing, usually 1...max.Many systems use an addressing scheme that groups two outputs. So 1 -> 0.1, 2 -> 0.2, 3 -> 1.1, 4 -> 1.2. (maybe a +1 is missing)

Ok so I have to map back when receiving from Z21 but I don't know how

**Comment by gfgit** [comment]
This helped me a bit: [Rocrail Docs](https://wiki.rocrail.net/doku.php?id=addressing:accessory-pg-en)

**Comment by gfgit** [comment]
> Ok so I have to map back when receiving from Z21 but I don't know how. I cannot use this code from `LanXSetTurnout` because I do not have the port in the `LAN_X_TURNOUT_INFO` reply
> 
> ```
> uint16_t linearAddress() const
> {
>   return (address() << 1) | port();
> }
> ```

If I omit the `port()` I get the feedback from Z21 but address 0 is ignored, address 1 to 7 go to the green row, all red rows are skipped in Output Keyboard

**Comment by reinder** [comment]
I was just reading the `LAN_X_TURNOUT_INFO` documentation. Think we need to evaluate `ZZ`.

`00` problably means both outputs are low
`01` problably means the first output of the pair is high or was last pulsed
`10` problably means the second output of the pair is high or was last pulsed

I wonder what happens if you set both outputs high, maybe it doesn't have support to control all outputs individually and always sets the other low. In that case we might need to add some extra stuff to the `OutputController` so output consumers can take that behavior into account.

**Comment by gfgit** [comment]
> Think we need to evaluate `ZZ`

As I understood, ZZ refers to a single "gate".
- 00 means unknown position (like at System boot)
- 01 is off
- 10 is on
- 11 is not valid

**Comment by reinder** [comment]
>     * Handling reply [Z21XNetReply.java#L100](https://github.com/JMRI/JMRI/blob/14c53f7cbbc2769b97fa8388f6142aa555a21574/java/src/jmri/jmrix/roco/z21/Z21XNetReply.java#L100)

Usually *Thrown* and *Closed* are two different physical output pins which share the same *turnout address*. Based on how JMRI handles it it seems that it only reports the physical output that is `1`.

We basically need a real z21 to test against and the verify if other z21 compatible behave the same.

**Comment by gfgit** [comment]
Hi, should we add a broadcast flag timer also to LocoNet interface when using Z21 IO Handler?
It's still UDP and without broadcast flags the LocoNet is useless...
How can we share common code with Z21 interface?

**Comment by reinder** [comment]
> Hi, should we add a broadcast flag timer also to LocoNet interface when using Z21 IO Handler? It's still UDP and without broadcast flags the LocoNet is useless... How can we share common code with Z21 interface?

Yes it should, broadcast flags should be set indeed and a keep alive.

I mainly added it because it is an option, don't know if it is useful though. Sharing code is not that easy, it isn't that much code so implement in similar is easier in this case.

**Comment by gfgit** [comment]
801ade92 fixes `LanXLocoInfo` checksum but it's not very elegant.
I would like to move the special code inside `XpressNet::isChecksumValid()` but to get XpressNet message length we need to know Z21 message length and substract 7.
It's not clear to me why `const int dataSize = n + 1; //n + xheader + db0` works.
It should be `n + 2` because `n` is 1-based and because there is the xheader byte. But then for loop has `i <= dataSize` so I guess it reads also last bit.

In a future commit I will handle firmware 1.42 which sends F29-F31 inside `db8` but make it conditional so we still support older firmware versions

**Comment by gfgit** [comment]
I'm getting new Udp pachet drops.
I'm starting to suspect this is related to `Z21ServerEmulator` doibg everithing in GUI thread. Which means ma y packet can accumulate before it's ready to process.
But also I would expecte Arduino imementation to be at least as slow a PC and maybe worse.
The problem can be tested with trains having many powered vehicles (say 10).
When you change direction, the first 2 or 3 get the new state while resta of the packets get dropped.
We could always expect a loco info response and re-send after a timeout expires without receiving anything but keeping track of responses could be difficult because other messages could arriver in the middle, even some that look like our responses but are cause by other throttle in the bus.
Another option would be to inser a small delay in the send queue like 10ms to lower traffic rate.

**Comment by gfgit** [comment]
Issues were on both Traintastic and ServerEmulator sides.
They are now fixed by recent commits plus PR #73
